
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    id_number VARCHAR(50) NOT NULL,
    country VARCHAR(100) NOT NULL,
    is_foreign BOOLEAN DEFAULT FALSE,
    password_hash VARCHAR(255) NOT NULL,
    balance DECIMAL(18,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sender_phone VARCHAR(20),
    receiver_phone VARCHAR(20),
    amount DECIMAL(18,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'USD',
    exchange_rate DECIMAL(10,4),
    type VARCHAR(50),
    status VARCHAR(20) DEFAULT 'completed',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE exchange_rates (
    id INT PRIMARY KEY AUTO_INCREMENT,
    from_currency VARCHAR(10),
    to_currency VARCHAR(10),
    rate DECIMAL(10,4),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admins (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- CREATE TABLE users (
--   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   full_name VARCHAR2(100),
--   phone_number VARCHAR2(20) UNIQUE,
--   id_number VARCHAR2(50),
--   nationality VARCHAR2(50),
--   wallet_balance NUMBER(10, 2)
-- );

