
-- CREATE TABLE users (
--   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   full_name VARCHAR2(100),
--   phone_number VARCHAR2(20) UNIQUE,
--   id_number VARCHAR2(50),
--   nationality VARCHAR2(50),
--   wallet_balance NUMBER(10, 2)
-- );

